# Generated by Django 5.2.6 on 2025-09-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cxc', 'Cuenta por Cobrar'), ('transferencia', 'Transferencia Bancaria'), ('otro', 'Otro')], default='efectivo', max_length=50, verbose_name='Forma de Pago'),
        ),
    ]
