# Generated by Django 5.2.6 on 2025-09-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creacion'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizacion'),
        ),
    ]
