# Generated by Django 5.2.6 on 2025-10-02 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_created_alter_orders_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(999999.99)]),
        ),
    ]
