# Generated by Django 5.2.6 on 2025-09-23 23:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(9999.99)])),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creacion')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizacion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
